## pragmas.nogc = true
require 'string'

do print '## Memory management'
  local str = tostring(1) -- tostring needs to allocates a new string
  print(str) -- outputs: 1
  str:destroy() -- deallocates the string
  print(str) -- the string was destroyed and is now empty, outputs nothing
end

local function get_multiple(): (boolean, integer)
  return false, 1
end

local a, b = get_multiple()
print(a,b) -- outputs: false 1

-- import "puts" from C library
local function puts(s: cstring <const>): cint <cimport>
  -- cannot have any code here, because this function is imported
end

local s21 = tostring(21)
puts(s21) -- outputs: hello