## pragmas.nogc = true
require 'string'

do print '## Memory management'
  local str = tostring(1) -- tostring needs to allocates a new string
  print(str) -- outputs: 1
  str:destroy() -- deallocates the string
  print(str) -- the string was destroyed and is now empty, outputs nothing
end

local function get_multiple(): (boolean, integer)
  return false, 1
end

local a, b = get_multiple()
print(a,b) -- outputs: false 1